# Generated by Django 2.1.1 on 2018-09-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=50, verbose_name='Бортовой номер')),
                ('info', models.CharField(max_length=512, verbose_name='Информация')),
                ('running_order_mass', models.FloatField(default=0, verbose_name='Снаряженная масса')),
                ('current_mass', models.FloatField(default=0, verbose_name='Текущий вес')),
                ('max_capacity', models.FloatField(default=0, verbose_name='Максимальная грузоподъемность')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название производителя')),
                ('code', models.CharField(max_length=256, verbose_name='Код производителя')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('web', models.CharField(max_length=512, verbose_name='Веб-сайт производителя')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название модели')),
                ('code', models.CharField(max_length=256, verbose_name='Код модели')),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.VehicleBrand', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('code', models.CharField(max_length=256, verbose_name='Код типа')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.VehicleType', verbose_name='Тип техники'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_vehicles', to='equipment.VehicleModel'),
        ),
    ]
