# Generated by Django 2.1.1 on 2018-09-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='running_order_mass',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='max_capacity',
            field=models.FloatField(default=0, verbose_name='Максимальная грузоподъемность'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='running_order_mass',
            field=models.FloatField(default=0, verbose_name='Снаряженная масса'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='equipment.VehicleBrand', verbose_name='Производитель'),
        ),
    ]
